# Retrieve multiple Node records
# GET  /nodes
# GET  /nodes/detail
# Intended scope(s): system, project
# Overridden: added role:admin
"baremetal:node:list_all": "role:admin or (role:reader and system_scope:all) or (role:service and system_scope:all) or rule:service_role"
