---
- name: Remove "--root-dev-only" from grub.cfg if OS is Rocky Linux 9
  hosts: overcloud
  become: yes
  gather_facts: true
  tasks:
    - block:
        - name: Check that /boot/efi/EFI/rocky/grub.cfg exists
          ansible.builtin.stat:
            path: /boot/efi/EFI/rocky/grub.cfg
          register: stat_result

        - name: Remove "--root-dev-only" from /boot/efi/EFI/rocky/grub.cfg
          ansible.builtin.replace:
            path: /boot/efi/EFI/rocky/grub.cfg
            regexp: '--root-dev-only\s?'
            replace: ''
          when: stat_result.stat.exists
      when:
        - ansible_facts['distribution'] == 'Rocky'
        - ansible_facts['distribution_major_version'] == '9'
