---
- name: Install pre-commit hooks
  hosts: localhost
  gather_facts: false
  vars:
    enable_pre_commit_hooks: false
  tasks:
    - name: Install pre-commit hooks
      block:
        - name: Install pre-commit hooks into kayobe virtual env
          ansible.builtin.pip:
            name: pre-commit
            version: 3.5.0
            virtualenv: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}"

        - name: Register pre-commit hooks with git
          ansible.builtin.command:
            cmd: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}/bin/pre-commit install"
            creates: "{{ lookup('ansible.builtin.env', 'KAYOBE_CONFIG_PATH') }}/../../.git/hooks/pre-commit"
          args:
            chdir: "{{ lookup('ansible.builtin.env', 'KAYOBE_CONFIG_PATH') }}"
