---
- name: Install pre-commit hooks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install pre-commit hooks
      block:
        - name: Install pre-commit hooks into kayobe virtual env
          ansible.builtin.pip:
            name: pre-commit
            version: 3.5.0
            virtualenv: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}"
          register: pip_install

        - name: Register pre-commit hooks with git
          ansible.builtin.command:
            cmd: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}/bin/pre-commit install"
          args:
            chdir: "{{ lookup('ansible.builtin.env', 'KAYOBE_CONFIG_PATH') }}"
          when: pip_install is changed
